### ISSUE TITLE
Window jumps to the right 15px when modal opens.

### ISSUE THREAD

**Issue by davidrichied** [kylefox/jquery-modal#150]
To stop the window from jumping 15px to the right, I added the following code to jquery.modal.js.
Before line 104: this.$body.css('padding-right','15px');
After line 123: this.$body.css('padding-right','0px');

The background still moves 15px to the right, but, at least, with the previous code, the body contents do not jump.

**Comment by kylefox** [comment]
I'm not sure if this is an implementation issue or a problem with jquery-modal itself. My guess is that it was related to your particular implementation. (Could confirm if you able to provide a test case).

Either way, thanks for posting the solution you found.

**Comment by davidrichied** [comment]
The issue also happens in Chrome, Firefox, and on my iPhone when viewing the modals on http://jquerymodal.com/

I implemented the modals into my website (with the fix) when the green "More Info" button is clicked: http://webpagearchitecture.com/
The background image is thrown way off on my website, possibly due to the fix. The strange thing is that this does not happen with any other modal.

If no one else has mentioned this issue, it might just be me.
Thanks for the response!

**Comment by davidrichied** [comment]
I figured it out... When the modal opens, the browser's scroll bar disappears, making the page shift to compensate for the missing scroll bar.

**Comment by pqvst** [comment]
Hmm, not a great solution...

1) the scroll bar will be visible on the page even if the page doesn't need scrolling
2) if the modal needs scroll, then two scrollbars will be visible

![preview](https://cloud.githubusercontent.com/assets/4990657/20557770/2d8ac5c6-b16d-11e6-9046-a0dda45a3000.png)

**Comment by humblecoder** [comment]
Still having this issue in Chrome, Safari, FF, and Opera.  Did we ever come up with a "pure" solution? 🤔

**Comment by ohmish** [comment]
This will leave the scrollbar as it was when Modal is opened (no jumping):

```
if ($(document).height() > $(window).height()) {
   this.$body.css('overflow','');
} else {
   this.$body.css('overflow','hidden');
}
```

Put that code instead of the `this.$body.css('overflow','hidden');` line in the block function.

It works, BUT it will also mess things up if the modal content is big.
